<a href="https://colab.research.google.com/github/thunguyen177/tutorials/blob/main/missing%20data%20imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## libraries and function 


In [33]:
# !pip install impyute
from sklearn import datasets
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from scipy import stats
import numpy as np
# import impyute as impy
from fancyimpute import IterativeSVD, SoftImpute, NuclearNormMinimization
import pandas as pd
import time

In [6]:
Xstar = np.array([[168, 30, 200],[200, 45, 300], [180, 90, np.nan], [129, 70, np.nan]])
Xstar

array([[168.,  30., 200.],
       [200.,  45., 300.],
       [180.,  90.,  nan],
       [129.,  70.,  nan]])

In [25]:
import numpy as np
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(Xstar)
print(imputer.transform(Xstar))

[[168.  30. 200.]
 [200.  45. 300.]
 [180.  90. 250.]
 [129.  70. 250.]]


In [26]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit_transform(Xstar)

array([[168.,  30., 200.],
       [200.,  45., 300.],
       [180.,  90., 250.],
       [129.,  70., 250.]])

In [28]:
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit_transform(Xstar)

array([[168.,  30., 200.],
       [200.,  45., 300.],
       [180.,  90., 250.],
       [129.,  70., 250.]])

In [30]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit_transform(Xstar)

array([[168.,  30., 200.],
       [200.,  45., 300.],
       [180.,  90., 200.],
       [129.,  70., 200.]])

In [3]:
!pip install fancyimpute
from fancyimpute import KNN, NuclearNormMinimization, SoftImpute, BiScaler 

In [8]:
X = KNN(k=1).fit_transform(Xstar)
print(X,'\n\n',Xstar)

Imputing row 1/4 with 0 missing, elapsed time: 0.001
[[168.  30. 200.]
 [200.  45. 300.]
 [180.  90. 300.]
 [129.  70. 200.]] 

 [[168.  30. 200.]
 [200.  45. 300.]
 [180.  90.  nan]
 [129.  70.  nan]]


In [11]:
# induce sparsity using singular value thresholding
X_incomplete_normalized = BiScaler().fit_transform(Xstar)
X = SoftImpute().fit_transform(X_incomplete_normalized)
print(X,'\n\n',X_incomplete_normalized)

[BiScaler] Initial log residual value = 12.065274
[BiScaler] Iter 1: log residual = -2.899786, log improvement ratio=14.965060
[BiScaler] Iter 2: log residual = -4.226582, log improvement ratio=1.326796
[BiScaler] Iter 3: log residual = -4.788862, log improvement ratio=0.562280
[BiScaler] Iter 4: log residual = -4.943716, log improvement ratio=0.154854
[BiScaler] Iter 5: log residual = -5.003397, log improvement ratio=0.059680
[BiScaler] Iter 6: log residual = -5.019292, log improvement ratio=0.015896
[BiScaler] Iter 7: log residual = -5.021997, log improvement ratio=0.002705
[BiScaler] Iter 8: log residual = -5.019859, log improvement ratio=-0.002139
[SoftImpute] Max Singular Value of X_init = 2.663978
[SoftImpute] Iter 1: observed MAE=0.021302 rank=2
[SoftImpute] Iter 2: observed MAE=0.021302 rank=2
[SoftImpute] Iter 3: observed MAE=0.021302 rank=2
[SoftImpute] Iter 4: observed MAE=0.021302 rank=2
[SoftImpute] Iter 5: observed MAE=0.021302 rank=2
[SoftImpute] Iter 6: observed MAE=0.0

In [14]:
# induce sparsity using singular value thresholding
X = SoftImpute(verbose = False).fit_transform(Xstar)
print(X,'\n\n',Xstar)

[[168.          30.         200.        ]
 [200.          45.         300.        ]
 [180.          90.         134.17830118]
 [129.          70.          90.70721687]] 

 [[168.  30. 200.]
 [200.  45. 300.]
 [180.  90.  nan]
 [129.  70.  nan]]


In [20]:
!pip install missingpy
# if ModuleNotFoundError: No module named 'sklearn.neighbors.base', use the following 3 lines
import sys
import sklearn.neighbors._base
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base

from missingpy import MissForest
# note that MissForest uses sklearn.__version__ 0.22.2.post1


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [22]:
X = MissForest(random_state=0).fit_transform(Xstar)
print(X,'\n\n',Xstar)


/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


Iteration: 0


/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


Iteration: 1
[[168.  30. 200.]
 [200.  45. 300.]
 [180.  90. 250.]
 [129.  70. 250.]] 

 [[168.  30. 200.]
 [200.  45. 300.]
 [180.  90.  nan]
 [129.  70.  nan]]


In [23]:
imputer = MissForest(random_state=0)
imputer.fit(Xstar)
X = imputer.transform(Xstar)
print(X,'\n\n',Xstar)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


Iteration: 0


/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


Iteration: 1
[[168.  30. 200.]
 [200.  45. 300.]
 [180.  90. 250.]
 [129.  70. 250.]] 

 [[168.  30. 200.]
 [200.  45. 300.]
 [180.  90.  nan]
 [129.  70.  nan]]


# Heart

In [31]:
data = pd.read_table('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECTF.train', header = None,sep=',')
test = pd.read_table('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECTF.test',
                     header=None, sep = ',')
data = pd.concat([data, test])
data = data.to_numpy()
X,y = data[:,1:], data[:,0]
X = X.astype(np.float32)
G = len(np.unique(y)) 
print(np.shape(X))
for g in range(G):
  print(sum(y==g))

(267, 44)
55
212


In [ ]:
def generate_nan(Xtrain, missing_rate):
  Xshape = Xtrain.shape
  na_id = np.random.randint(0,Xtrain.size,round(missing_rate*Xtrain.size))
  Xtr_nan = Xtrain.flatten()
  Xtr_nan[na_id] = np.nan 
  return Xtr_nan.reshape(Xshape)

In [35]:
Xstar = generate_nan(X, 0.2)
Xstar[:3]

array([[59., 52., 70., nan, 73., 66., 72., 61., 58., 52., 72., 71., 70.,
        77., 66., 65., 67., 55., 61., 57., 68., 66., 72., 74., 63., 64.,
        56., 54., 67., 54., 76., 74., 65., nan, 66., 56., 62., 56., 72.,
        62., 74., 74., nan, 67.],
       [72., 62., 69., 67., 78., 82., 74., 65., 69., 63., 70., 70., 72.,
        74., 70., 71., 72., 75., 66., 65., 73., 78., 74., nan, 74., 69.,
        69., 70., 71., 69., 72., nan, 62., nan, 65., 71., 63., 60., 69.,
        73., 67., 71., nan, 58.],
       [nan, 62., 70., 64., 67., 64., 79., 65., 70., nan, 72., 71., 68.,
        nan, 61., 61., 73., 71., 75., 74., 80., 74., 54., 47., 53., 37.,
        77., 68., 72., 59., 72., 68., nan, 60., 73., nan, 66., 65., 64.,
        nan, nan, nan, nan, 46.]], dtype=float32)

# seeds 

In [ ]:
data = pd.read_table('https://archive.ics.uci.edu/ml/machine-learning-databases/00236/seeds_dataset.txt',
                     sep = '\s+', header = None)
data = pd.DataFrame.to_numpy(data)
X,y = data[:,:7], data[:,7]-1 # reset the labels to go start from 0  